name: Convert AdGuard to OpenClash

on:
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AdGuard blocklist
        run: |
          echo "Downloading AdGuard DNS filter..."
          curl -s 'https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt' -o adguard_base_filter.txt

      - name: Convert to OpenClash YAML
        run: |
          echo "Converting AdGuard DNS filter to OpenClash YAML..."

          # Add header and start payload
          echo "# OpenClash AdGuard: https://github.com/AyraHikari/openclash_adguard" > adguard_openclash.yaml
          echo "# Updated at: $(date +'%H:%M %d/%m/%Y')" >> adguard_openclash.yaml
          echo " " >> adguard_openclash.yaml
          echo "payload:" >> adguard_openclash.yaml

          # Process all downloaded files
          for file in adguard_*_filter.txt; do
            # Process block rules (starting with ||)
            grep -E '^[|][|]' "$file" |
              sed 's/^||//' |
              sed -E 's/[/].*$//' |
              sed -E 's/\$.*$//' |
              sed -E 's/\^.*$//' |
              sed 's/\$dnsrewrite=0\.0\.0\.0//' |
              awk '!seen[$0]++' |
              sed '/^$/d' |
              sed 's/^/  - DOMAIN-SUFFIX,/' >> adguard_openclash.yaml
            
            # Process exception rules (starting with @@)
            echo " " >> adguard_openclash.yaml
            echo "# Exceptions from $file:" >> adguard_openclash.yaml
            grep -E '^@@[|][|]' "$file" |
              sed 's/^@@||//' |
              sed -E 's/[/].*$//' |
              sed -E 's/\$.*$//' |
              sed -E 's/\^.*$//' |
              awk '!seen[$0]++' |
              sed '/^$/d' |
              sed 's/^/  - DOMAIN-SUFFIX,/' >> adguard_openclash.yaml
          done

          echo "Conversion complete."

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update OpenClash YAML from AdGuard blocklist"
          file_pattern: |
            adguard_openclash.yaml
            adguard_*_filter.txt
